// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nandagcrqikmqqtysvvw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5hbmRhZ2NycWlrbXFxdHlzdnZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NTY4NjIsImV4cCI6MjA2NjUzMjg2Mn0.ZJ6v2EIOo6Dj1Bj8__pqW2YkOsp38iD64T06hxKPKvs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);